version: '3.8'

services:
  odin-postgres:
    image: postgres:17.5
    container_name: odin-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - odindata:/var/lib/postgresql/data

volumes:
  odindata: