spring:
  application.name: OdinService
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9001

email:
  provider: sendgrid
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    from-email: ${FROM_EMAIL}